# 应用服务 WEB 访问端口
server.port=8080
#???????????(???????? trace < debug < info < warn < error)
logging.level.helloWorldController=warn

#????????????spring???????log?????? spring.log ??????
logging.file.path=/home/ljj/jiaotou/logs

#?????????(logging.path?logging.file ??????)
#logging.file=E:/springboot.log
logging.file.name=/home/ljj/jiaotou/logs/m.log

# ?????????????????????
#logging.pattern.console=%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n
# ??????????????????????
#logging.pattern.file=%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n
